### ISSUE TITLE
What attribute is needed for Autoplay to work?

### ISSUE THREAD

**Issue by Marcos-Bernasconi** [nuxt-modules/cloudinary#242]
```
  <CldVideoPlayer
              muted
              loop
              :controls="false"
              autoplay
              autoPlay="always"
              width="1920"
              height="1080"
              src="IdVideo"
            />
```

I have tried using these:
-  `autoPlay`: on-scroll and always
- :playsinline="true" 
-  :autoplay="true"
Am I missing some attributes or props to make the video autoplay correctly?

**Comment by Baroshem** [comment]
Hey there, sorry for not answering but I was on Vue.js DE conference.

Thanks for reporting this issue. I think the prop is missing from declaration of props in a vue component. Quite strange because I remember adding it but maybe it was removed at some point.

Would you be interested in contributing and adding it? I can provide all help needed :) 

If not, no worries. I can also add it myself :)

**Comment by Marcos-Bernasconi** [comment]
Hi! I would love to contribute, thank you very much =)
I will try my best and let you know how it goes.
